CREATE OR REPLACE FUNCTION VECTOR_DISTANCE(VARBINARY(6200), VARBINARY(6200)) 
    RETURNS REAL
    EXTERNAL NAME 'similarityudf!VECTOR_DISTANCE'
    FENCED
    CALLED ON NULL INPUT
    NOT VARIANT
    READS SQL DATA
    PARAMETER STYLE DB2SQL
    LANGUAGE C
    NO EXTERNAL ACTION;
    
CREATE OR REPLACE FUNCTION VECTOR_LEN(VARBINARY(6200)) 
    RETURNS SMALLINT
    EXTERNAL NAME 'similarityudf!VECTOR_LEN'
    FENCED
    CALLED ON NULL INPUT
    NOT VARIANT
    READS SQL DATA
    PARAMETER STYLE DB2SQL
    LANGUAGE C
    NO EXTERNAL ACTION;

CREATE OR REPLACE FUNCTION VEC_TO_CHAR(VARBINARY(6200)) 
    RETURNS VARCHAR(10200)
    EXTERNAL NAME 'similarityudf!VEC_TO_CHAR'
    FENCED
    CALLED ON NULL INPUT
    NOT VARIANT
    READS SQL DATA
    PARAMETER STYLE DB2SQL
    LANGUAGE C
    NO EXTERNAL ACTION;

CREATE OR REPLACE FUNCTION CHAR_TO_VEC(VARCHAR(10200)) 
    RETURNS VARBINARY(6144)
    EXTERNAL NAME 'similarityudf!CHAR_TO_VEC'
    FENCED
    CALLED ON NULL INPUT
    NOT VARIANT
    READS SQL DATA
    PARAMETER STYLE DB2SQL
    LANGUAGE C
    NO EXTERNAL ACTION;

CONNECT RESET;
