CONNECT TO DB2AI;

DROP TABLE FLIGHTS_TRAIN;
DROP TABLE FLIGHTS_TEST;

CREATE TABLE FLIGHTS_TRAIN  (
		  "YEAR" INTEGER , 
		  "QUARTER" INTEGER , 
		  "MONTH" INTEGER , 
		  "DAYOFMONTH" INTEGER , 
		  "DAYOFWEEK" INTEGER , 
		  "UNIQUECARRIER" VARCHAR(50 OCTETS) , 
		  "ORIGIN" VARCHAR(50 OCTETS) , 
		  "DEST" VARCHAR(50 OCTETS) , 
		  "CRSDEPTIME" INTEGER , 
		  "DEPTIME" INTEGER , 
		  "DEPDELAY" REAL , 
		  "DEPDEL15" REAL , 
		  "TAXIOUT" INTEGER , 
		  "WHEELSOFF" INTEGER , 
		  "CRSARRTIME" INTEGER , 
		  "CRSELAPSEDTIME" INTEGER , 
		  "AIRTIME" INTEGER , 
		  "DISTANCEGROUP" INTEGER , 
		  "FLIGHTSTATUS" INTEGER ); 


CREATE TABLE FLIGHTS_TEST  (
		  "YEAR" INTEGER , 
		  "QUARTER" INTEGER , 
		  "MONTH" INTEGER , 
		  "DAYOFMONTH" INTEGER , 
		  "DAYOFWEEK" INTEGER , 
		  "UNIQUECARRIER" VARCHAR(50 OCTETS) , 
		  "ORIGIN" VARCHAR(50 OCTETS) , 
		  "DEST" VARCHAR(50 OCTETS) , 
		  "CRSDEPTIME" INTEGER , 
		  "DEPTIME" INTEGER , 
		  "DEPDELAY" REAL , 
		  "DEPDEL15" REAL , 
		  "TAXIOUT" INTEGER , 
		  "WHEELSOFF" INTEGER , 
		  "CRSARRTIME" INTEGER , 
		  "CRSELAPSEDTIME" INTEGER , 
		  "AIRTIME" INTEGER , 
		  "DISTANCEGROUP" INTEGER , 
		  "FLIGHTSTATUS" INTEGER );

LOAD FROM FLIGHTS_TRAIN.del OF DEL INSERT INTO FLIGHTS_TRAIN;

LOAD FROM FLIGHTS_TEST.del OF DEL INSERT INTO FLIGHTS_TEST;
	         
CONNECT RESET;       	
